var museen = [
	{
		"bezeichnung": "",
		"typ": "historisch, zeitgenössisch",
		"beschreibung": "",
		"adresse": "",
		"ort": "",
		"telefon": "",
		"longitude": ,
		"latitude": ,
		"url": "",
		"email": "",
		"image": "",
		"imageAktuell": "",
		"eintritt": "",
		"oeffnungszeiten": "",
		"ausstellungDatum": "",
		"ausstellungTitel": "",
		"urlAusstellung": ""
	},
	{
		"bezeichnung": "",
		"typ": "historisch, zeitgenössisch",
		"beschreibung": "",
		"adresse": "",
		"ort": "",
		"telefon": "",
		"longitude": ,
		"latitude": ,
		"url": "",
		"email": "",
		"image": "",
		"imageAktuell": "",
		"eintritt": "",
		"oeffnungszeiten": "",
		"ausstellungDatum": "",
		"ausstellungTitel": "",
		"urlAusstellung": ""
	}
];
